In [ ]:
import numpy as np
import time
import sys

In [20]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
s = range(1000)

In [23]:
print(s)

range(0, 1000)


In [24]:
print(sys.getsizeof(5)*len(s))

28000


In [11]:
d = np.arange(1000)

In [14]:
print(d.size*d.itemsize)

4000


In [25]:
size  = 1000

l1 = range(size)
l2 = range(size)
a1 =np.arange(size)
a2 = np.arange(size)

start = time.time()

result = [(x,y) for x,y in zip(l1,l2)]

endlist = time.time()

result2 = a1 + a2

endarray = time.time()

print (start*1000)
print (endlist*1000)
print (endarray)

1638368653474.876
1638368653848.6218
1638368653.8486218


In [27]:
a.dtype

dtype('int32')

In [28]:
a.shape

(2, 3)

In [30]:
a = np.linspace(1,10,100)

In [31]:
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [32]:
np.sqrt(a)

array([1.        , 1.04446594, 1.08711461, 1.12815215, 1.16774842,
       1.20604538, 1.24316312, 1.2792043 , 1.31425748, 1.34839972,
       1.38169856, 1.41421356, 1.44599761, 1.47709789, 1.50755672,
       1.53741223, 1.5666989 , 1.59544807, 1.62368828, 1.65144565,
       1.67874412, 1.70560573, 1.73205081, 1.75809815, 1.78376517,
       1.80906807, 1.83402191, 1.85864075, 1.88293774, 1.90692518,
       1.9306146 , 1.95401684, 1.97714211, 2.        , 2.02259959,
       2.04494943, 2.06705764, 2.08893187, 2.11057941, 2.13200716,
       2.15322169, 2.17422923, 2.19503572, 2.21564684, 2.23606798,
       2.2563043 , 2.27636073, 2.29624199, 2.31595258, 2.33549683,
       2.35487888, 2.3741027 , 2.39317211, 2.41209076, 2.43086217,
       2.44948974, 2.46797672, 2.48632624, 2.50454133, 2.5226249 ,
       2.54057975, 2.5584086 , 2.57611406, 2.59369866, 2.61116484,
       2.62851496, 2.64575131, 2.66287609, 2.67989145, 2.69679945,
       2.7136021 , 2.73030135, 2.74689908, 2.76339712, 2.77979

In [33]:
np.std(a)

2.624188186156556

In [34]:
a.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [35]:
np.sin(a)

array([ 0.84147098,  0.88704699,  0.92529707,  0.95590534,  0.978619  ,
        0.99325047,  0.99967891,  0.99785123,  0.98778253,  0.96955595,
        0.94332203,  0.90929743,  0.86776314,  0.8190622 ,  0.76359681,
        0.70182505,  0.63425707,  0.56145091,  0.48400786,  0.40256749,
        0.31780241,  0.23041267,  0.14112001,  0.05066187, -0.04021468,
       -0.1307591 , -0.22022362, -0.30786935, -0.39297247, -0.47483011,
       -0.55276624, -0.6261372 , -0.69433703, -0.7568025 , -0.8130177 ,
       -0.86251837, -0.9048957 , -0.93979971, -0.96694212, -0.98609877,
       -0.99711147, -0.99988924, -0.99440916, -0.98071647, -0.95892427,
       -0.92921254, -0.89182665, -0.84707537, -0.79532828, -0.73701276,
       -0.67261042, -0.60265314, -0.52771868, -0.44842592, -0.36542971,
       -0.2794155 , -0.19109366, -0.10119362, -0.01045784,  0.0803643 ,
        0.17052273,  0.25927286,  0.34588171,  0.429634  ,  0.50983804,
        0.58583144,  0.6569866 ,  0.72271585,  0.78247636,  0.83

In [36]:
np.pi

3.141592653589793

In [37]:
np.sin(np.pi)

1.2246467991473532e-16

In [38]:
np.sin(90)

0.8939966636005579

In [39]:
np.cos(0)

1.0

In [40]:
np.sin(0)

0.0

In [41]:
np.sin(180)

-0.8011526357338304

In [42]:
np.exp(1)

2.718281828459045

In [43]:
np.exp(10)

22026.465794806718

In [46]:
np.log(np.exp(2))

2.0