In [26]:
import numpy as np
import sys

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [28]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a[1,5]

13

In [30]:
a[1,-2]

13

In [31]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
a[:,1]

array([2, 9])

In [33]:
a[:,0]

array([1, 8])

In [34]:
a[:,2]

array([ 3, 10])

In [35]:
a[1:5:2,:]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [38]:
a[0,1:6:2]

array([2, 4, 6])

In [42]:
a[1,5]

15

In [43]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 15, 14]])

In [46]:
a

array([[ 1,  2, -1,  4,  5,  6,  7],
       [ 8,  9, -1, 11, 12, 15, 14]])

In [48]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [50]:
b.shape

(2, 2, 2)

In [51]:
b.ndim

3

In [52]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
b[0,1,1]

4

In [55]:
b[:,1,:]=[[9,9],[8,8]]

In [56]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [60]:
b[0,0,0]=3.7

In [61]:
b

array([[[3, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [65]:
np.zeros((4,4,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [67]:
np.ones(2,dtype='int32')

array([1, 1])

In [69]:
np.full((2,2),999.)

array([[999., 999.],
       [999., 999.]])

In [74]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [78]:
np.random.rand(100)

array([0.28035897, 0.12689134, 0.78941193, 0.88884528, 0.76811398,
       0.63504964, 0.8543793 , 0.49223431, 0.24429881, 0.30594014,
       0.38434082, 0.28959909, 0.42175973, 0.12357518, 0.98058081,
       0.48471333, 0.8583582 , 0.38754645, 0.07936387, 0.91217691,
       0.33542264, 0.1929028 , 0.18670798, 0.95150423, 0.75231001,
       0.51543648, 0.94055488, 0.43737993, 0.40545335, 0.46121166,
       0.18932025, 0.92724229, 0.4214792 , 0.63623637, 0.28351127,
       0.62310953, 0.93404609, 0.8661705 , 0.23097405, 0.86326604,
       0.75139914, 0.22434247, 0.58111354, 0.83000827, 0.38896352,
       0.01265846, 0.04996491, 0.59705956, 0.65940362, 0.80849157,
       0.0241199 , 0.38926627, 0.02532067, 0.26330125, 0.41535979,
       0.10214607, 0.47456398, 0.87275971, 0.04429448, 0.18090475,
       0.90268682, 0.14851888, 0.91439987, 0.60226687, 0.4965221 ,
       0.80281224, 0.75550154, 0.90840657, 0.80106613, 0.68719902,
       0.56346953, 0.96419661, 0.89387022, 0.27487861, 0.99567

In [83]:
np.random.randint(100,199,size=(3,3))

array([[132, 167, 130],
       [154, 126, 161],
       [182, 126, 181]])

In [84]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
r1=np.repeat(a,3)

In [87]:
r1

array([ 1,  1,  1,  2,  2,  2, -1, -1, -1,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, -1, -1, -1, 11, 11, 11, 12,
       12, 12, 15, 15, 15, 14, 14, 14])

In [88]:
a=np.zeros((5,5))

In [89]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
a[2,2]=9

In [91]:
a[:0]=1

In [92]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
a[:,0]=1

In [94]:
a[0,:]=1

In [95]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 9., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [96]:
a[:,4]=1

In [97]:
a[4,:]=1

In [98]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
x = np.full((3,3),2)

In [100]:
x

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [105]:
a[1:4,1:4]=x

In [106]:
a[2,2]=-1

In [107]:
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  2.,  2.,  1.],
       [ 1.,  2., -1.,  2.,  1.],
       [ 1.,  2.,  2.,  2.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [108]:
a =np.array([1,2,3])

In [109]:
a

array([1, 2, 3])

In [110]:
b = a

In [111]:
b

array([1, 2, 3])

In [112]:
a[1]=-3

In [113]:
b

array([ 1, -3,  3])

In [115]:
c=np.copy(a)

In [116]:
c

array([ 1, -3,  3])

In [117]:
a[1]=100

In [118]:
c

array([ 1, -3,  3])

In [119]:
b

array([  1, 100,   3])

In [120]:
a = np.array([1,2,3,4])

In [121]:
a +1

array([2, 3, 4, 5])

In [122]:
a*2

array([2, 4, 6, 8])

In [123]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [124]:
a*2

array([2, 4, 6, 8])

In [125]:
a

array([1, 2, 3, 4])

In [126]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [127]:
b = np.array([1,0,1,0])

In [128]:
a+b

array([2, 2, 4, 4])

In [129]:
a*b

array([1, 0, 3, 0])

In [130]:
sin(a)

NameError: name 'sin' is not defined

In [131]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [132]:
a = np.ones((2,3))

In [134]:
b=np.full((3,2),2)

In [135]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [136]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [138]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [139]:
c = np.identity(3)

In [144]:
np.linalg.det(c)

1.0

In [145]:
stats = np.array([[1,2,3],[4,5,6]])

In [146]:
np.min(stats)

1

In [148]:
np.mean(stats)

3.5

In [150]:
np.max(stats[0])

3

In [154]:
np.max(stats, axis=1)

array([3, 6])

In [156]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [157]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [160]:
b = a.reshape((4,2))

In [161]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [162]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [165]:
np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [166]:
np.hstack([v1,v1,v2])

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8])

In [172]:
data = np.genfromtxt('RandomNumbers.csv', delimiter=',')

In [188]:
data[~((data > 90) & (data < 95))]

array([        nan, 35.68424253, 21.145625  , 15.08220141,  9.56687831,
        8.14391552, 96.41665711, 59.24431624, 16.04750772, 26.09521035,
       17.16448917, 68.58861764, 13.19537772, 43.9420979 , 57.96933115,
       73.57979137, 66.68866491, 70.53791231, 16.18030176, 78.41162157,
       96.34125044, 98.83510659, 52.58659904,  4.58479085, 32.25041616,
       36.32619268,  8.6793296 , 83.71150549, 24.09989956, 65.74708734,
       42.38837354, 79.51799966, 88.01409131, 54.679935  , 96.3755596 ,
       17.30774843, 97.51197977, 63.81398429, 35.29757267, 81.5021318 ,
       35.48855594, 47.66938536, 85.06431779, 86.56224563, 75.80500195,
       43.62888738, 60.73447809, 56.61141265, 60.76026861, 71.02977592,
       68.84409549, 97.29687054, 51.80579706, 16.63176095, 61.00551896,
        5.51439571,  8.94506727, 80.40465293, 20.36521056, 56.49210362,
       64.15036598, 71.94893736, 53.73687181, 84.74870355, 29.63399138,
       24.05102818, 25.55194954,  1.90276526, 58.79901503, 79.50

In [183]:
np.all(data > 30, axis =1)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

[[0,4,5],[3,4]]
